### PR TITLE
express-delete | Rich Trunzo

### PR DESCRIPTION
**Pull request by richtrunzo**
Screen Shot 2021-01-06 at 5 35 50 PM
Screen Shot 2021-01-06 at 5 36 02 PM

### CODE REVIEW

**Review by BrettAlbright — CHANGES_REQUESTED** [review]
Hey Rich, good initial attempts, but you should be deleting the grade which matches the supplied id. so If someone wants to delete id 273, they need to enter 273

**Comment by richtrunzo** [comment]
Updated per your feedback! 

Screen Shot 2021-01-06 at 5 50 25 PM
Screen Shot 2021-01-06 at 5 48 54 PM
Screen Shot 2021-01-06 at 5 49 02 PM

**Comment by richtrunzo** [comment]
Updated and removed conditional statement.
Screen Shot 2021-01-06 at 6 03 41 PM
Screen Shot 2021-01-06 at 6 03 49 PM
Screen Shot 2021-01-06 at 6 03 57 PM

**Review by BrettAlbright — APPROVED** [review]
👍

**Pull request merged**
